language: php
sudo: false

matrix:
  include:
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

addons:
  sonarcloud:
    organization: "kreait"

git:
  depth: false

before_install:
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then
      openssl aes-256-cbc -K $encrypted_8bfcfbcad9c4_key -iv $encrypted_8bfcfbcad9c4_iv -in test_credentials.json.enc -out tests/_fixtures/test_credentials.json -d;
      openssl aes-256-cbc -K $encrypted_d51fa485ef84_key -iv $encrypted_d51fa485ef84_iv -in test_devices.json.enc -out tests/_fixtures/test_devices.json -d;
    fi

install:
  - composer update $COMPOSER_FLAGS --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/phpstan analyse -c phpstan.neon.dist --no-progress
  - vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
